### PR TITLE
Fixes #13 and small changes

### LINKED ISSUE #13: Port input not working
```
What steps will reproduce the problem?
1. Create a session
2. Change the port
3. Try activation the session or look in PuTTY

What is the expected output? What do you see instead?
The entered port should be used and displayed in PuTTY. It is not (it remains 
"22").

What version of the product are you using? On what operating system?
0.9.1, Windows 7 Professional


```

Original issue reported on code.google.com by `andrerdn...@googlemail.com` on 18 Jan 2012 at 9:53

### PR DESCRIPTION
**Pull request by SommerEngineering**
- Fixes issue #13 
- Re-added the original MIT license
- Re-added the original Visual Studio solution file
- Added a .gitignore file
- Added a section to the readme where I point to the original source code
- Changed the .NET framework to 4.5.2 (which is default on Windows 10)
- Increased the release number

### CODE REVIEW

**Comment by kostapc** [comment]
Thanx for PR!
Why switch to NET 4.5? This app is really simple and can work on win7 by default (NET 3.5).

**Comment by SommerEngineering** [comment]
@kostapc Okay, you are right. .NET 3.5 is better for non-Windows 10 users. Within Visual Studio, the switch back to 3.5 is no issue. Should I switch the framework with a new PR or do you want to switch?

**Comment by kostapc** [comment]
@SommerEngineering i'll swith by myself, without additional PR. For keep history clear.

**Comment by kostapc** [comment]
done. And old .sln, .csproj files removed.

**Pull request merged**
